name: Run Tests

on:
  push:
    branches: main
    paths:
      - 'README.md'
      - 'Cargo.toml'
      - 'src/**.rs'
      - 'tests/**.rs'
  pull_request:
    branches: main
    paths:
      - 'README.md'
      - 'Cargo.toml'
      - 'src/**.rs'
      - 'tests/**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --check
    - name: Build Debug
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: Lint Code
      uses: actions-rs/cargo@v1
      with:
        command: clippy
    - name: Run Tests on Debug
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: Build Release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Run Tests on Release
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release
  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nightly Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: miri
      - name: Setup Miri
        uses: actions-rs/cargo@v1
        with:
          command: miri
          args: setup
      - name: Run Miri
        uses: actions-rs/cargo@v1
        with:
          command: miri
          args: test
