name: Latest Stable Rust

on:
  push:
    branches: main
    paths:
      - 'README.md'
      - 'Cargo.toml'
      - 'src/**.rs'
      - 'tests/**.rs'
  pull_request:
    branches: main
    paths:
      - 'README.md'
      - 'Cargo.toml'
      - 'src/**.rs'
      - 'tests/**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --check
    - name: Build Debug
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: Lint Code
      uses: actions-rs/cargo@v1
      with:
        command: clippy
    - name: Run Tests on Debug
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: Build Release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Run Tests on Release
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release
