name: Run Tests

on:
  push:
    branches: main
    paths:
      - 'README.md'
      - 'Cargo.toml'
      - 'src/**.rs'
      - 'tests/**.rs'
  pull_request:
    branches: main
    paths:
      - 'README.md'
      - 'Cargo.toml'
      - 'src/**.rs'
      - 'tests/**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - name: Check Format
      run: cargo fmt --check
    - name: Build Debug
      run: cargo build
    - name: Lint Code
      run: cargo clippy
    - name: Run Tests on Debug
      run: cargo test
    - name: Build Release
      run: cargo build --release
    - name: Run Tests on Release
      run: cargo test --release
  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - name: Setup Miri
        run: cargo miri setup
      - name: Run Miri
        run: cargo miri test
